// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1W37CBTRwSJWyaxmnzSodp_ydzYyOF8k',
    appId: '1:732644826714:web:2e3c6681c814e790f78263',
    messagingSenderId: '732644826714',
    projectId: 'iassignment2-31931',
    authDomain: 'iassignment2-31931.firebaseapp.com',
    storageBucket: 'iassignment2-31931.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvYzmrP41vaBBTgOVKoVJHTTL9lQfHKvs',
    appId: '1:732644826714:android:d2c7171ac7461024f78263',
    messagingSenderId: '732644826714',
    projectId: 'iassignment2-31931',
    storageBucket: 'iassignment2-31931.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr70q1PHWftOOZONdaQPiU8aWCA6xHqMs',
    appId: '1:732644826714:ios:2869c6ea560ba98cf78263',
    messagingSenderId: '732644826714',
    projectId: 'iassignment2-31931',
    storageBucket: 'iassignment2-31931.firebasestorage.app',
    iosBundleId: 'com.example.assignment2',
  );

}